version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: gtm
      POSTGRES_PASSWORD: gtm
      POSTGRES_DB: gtm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: postgresql+psycopg://gtm:gtm@db:5432/gtm
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID:-}
      REDDIT_SECRET: ${REDDIT_SECRET:-}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
      ENV: docker
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: bash -lc "poetry install && poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000"

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: postgresql+psycopg://gtm:gtm@db:5432/gtm
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ENV: docker
    depends_on:
      - db
      - redis
    command: bash -lc "poetry install && poetry run celery -A src.workers.celery_app.celery_app worker --loglevel=INFO"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: bash -lc "pnpm install && pnpm dev --host"

volumes:
  db_data:
